/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessEntitlement {
  'startTime' : bigint,
  'status' : AccessRequestStatus,
  'endTime' : [] | [bigint],
  'source' : EntitlementSource,
  'user' : UserId,
  'entitlementType' : EntitlementType,
  'requestTimestamp' : bigint,
}
export type AccessRequestStatus = { 'expired' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ChatMessage {
  'id' : MessageId,
  'deleted' : boolean,
  'content' : string,
  'sender' : UserId,
  'timestamp' : bigint,
}
export interface ChatThreadView {
  'id' : ThreadId,
  'participants' : Array<UserId>,
  'messages' : Array<ChatMessage>,
}
export type EntitlementSource = { 'promotion' : null } |
  { 'adminGrant' : null } |
  { 'payment' : null };
export type EntitlementType = { 'trial' : null } |
  { 'permanent' : null } |
  { 'subscription' : null } |
  { 'sponsored' : null };
export type MessageId = bigint;
export type ThreadId = bigint;
export type UserId = Principal;
export interface UserProfile {
  'principal' : UserId,
  'displayName' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveAccessRequest' : ActorMethod<[UserId, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[UserId], undefined>,
  'createThread' : ActorMethod<[Array<UserId>], ThreadId>,
  'deleteMessage' : ActorMethod<[ThreadId, MessageId], undefined>,
  'deleteThread' : ActorMethod<[ThreadId], undefined>,
  'editMessage' : ActorMethod<[ThreadId, MessageId, string], undefined>,
  'getAccessEntitlement' : ActorMethod<[UserId], [] | [AccessEntitlement]>,
  'getAllAccessEntitlements' : ActorMethod<[], Array<AccessEntitlement>>,
  'getBlockedUsers' : ActorMethod<[], Array<UserId>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentUserAccessEntitlement' : ActorMethod<[], [] | [AccessEntitlement]>,
  'getMessages' : ActorMethod<[ThreadId], Array<ChatMessage>>,
  'getThread' : ActorMethod<[ThreadId], ChatThreadView>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserThreads' : ActorMethod<[], Array<ThreadId>>,
  'grantAccess' : ActorMethod<
    [UserId, EntitlementType, EntitlementSource, [] | [bigint]],
    undefined
  >,
  'hasAccess' : ActorMethod<[], boolean>,
  'hasBlocked' : ActorMethod<[UserId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[[] | [string]], UserProfile>,
  'requestAccess' : ActorMethod<[], boolean>,
  'revokeAccess' : ActorMethod<[UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[ThreadId, string], MessageId>,
  'switchToTemporaryAccess' : ActorMethod<[UserId, bigint], undefined>,
  'unblockUser' : ActorMethod<[UserId], undefined>,
  'userExists' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];