/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ThreadId = IDL.Nat;
export const MessageId = IDL.Nat;
export const AccessRequestStatus = IDL.Variant({
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const EntitlementSource = IDL.Variant({
  'promotion' : IDL.Null,
  'adminGrant' : IDL.Null,
  'payment' : IDL.Null,
});
export const EntitlementType = IDL.Variant({
  'trial' : IDL.Null,
  'permanent' : IDL.Null,
  'subscription' : IDL.Null,
  'sponsored' : IDL.Null,
});
export const AccessEntitlement = IDL.Record({
  'startTime' : IDL.Int,
  'status' : AccessRequestStatus,
  'endTime' : IDL.Opt(IDL.Int),
  'source' : EntitlementSource,
  'user' : UserId,
  'entitlementType' : EntitlementType,
  'requestTimestamp' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'principal' : UserId,
  'displayName' : IDL.Opt(IDL.Text),
});
export const ChatMessage = IDL.Record({
  'id' : MessageId,
  'deleted' : IDL.Bool,
  'content' : IDL.Text,
  'sender' : UserId,
  'timestamp' : IDL.Int,
});
export const ChatThreadView = IDL.Record({
  'id' : ThreadId,
  'participants' : IDL.Vec(UserId),
  'messages' : IDL.Vec(ChatMessage),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveAccessRequest' : IDL.Func([UserId, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([UserId], [], []),
  'createThread' : IDL.Func([IDL.Vec(UserId)], [ThreadId], []),
  'deleteMessage' : IDL.Func([ThreadId, MessageId], [], []),
  'deleteThread' : IDL.Func([ThreadId], [], []),
  'editMessage' : IDL.Func([ThreadId, MessageId, IDL.Text], [], []),
  'getAccessEntitlement' : IDL.Func(
      [UserId],
      [IDL.Opt(AccessEntitlement)],
      ['query'],
    ),
  'getAllAccessEntitlements' : IDL.Func(
      [],
      [IDL.Vec(AccessEntitlement)],
      ['query'],
    ),
  'getBlockedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUserAccessEntitlement' : IDL.Func(
      [],
      [IDL.Opt(AccessEntitlement)],
      ['query'],
    ),
  'getMessages' : IDL.Func([ThreadId], [IDL.Vec(ChatMessage)], ['query']),
  'getThread' : IDL.Func([ThreadId], [ChatThreadView], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserThreads' : IDL.Func([], [IDL.Vec(ThreadId)], ['query']),
  'grantAccess' : IDL.Func(
      [UserId, EntitlementType, EntitlementSource, IDL.Opt(IDL.Int)],
      [],
      [],
    ),
  'hasAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'hasBlocked' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([IDL.Opt(IDL.Text)], [UserProfile], []),
  'requestAccess' : IDL.Func([], [IDL.Bool], []),
  'revokeAccess' : IDL.Func([UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([ThreadId, IDL.Text], [MessageId], []),
  'switchToTemporaryAccess' : IDL.Func([UserId, IDL.Int], [], []),
  'unblockUser' : IDL.Func([UserId], [], []),
  'userExists' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ThreadId = IDL.Nat;
  const MessageId = IDL.Nat;
  const AccessRequestStatus = IDL.Variant({
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const EntitlementSource = IDL.Variant({
    'promotion' : IDL.Null,
    'adminGrant' : IDL.Null,
    'payment' : IDL.Null,
  });
  const EntitlementType = IDL.Variant({
    'trial' : IDL.Null,
    'permanent' : IDL.Null,
    'subscription' : IDL.Null,
    'sponsored' : IDL.Null,
  });
  const AccessEntitlement = IDL.Record({
    'startTime' : IDL.Int,
    'status' : AccessRequestStatus,
    'endTime' : IDL.Opt(IDL.Int),
    'source' : EntitlementSource,
    'user' : UserId,
    'entitlementType' : EntitlementType,
    'requestTimestamp' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'principal' : UserId,
    'displayName' : IDL.Opt(IDL.Text),
  });
  const ChatMessage = IDL.Record({
    'id' : MessageId,
    'deleted' : IDL.Bool,
    'content' : IDL.Text,
    'sender' : UserId,
    'timestamp' : IDL.Int,
  });
  const ChatThreadView = IDL.Record({
    'id' : ThreadId,
    'participants' : IDL.Vec(UserId),
    'messages' : IDL.Vec(ChatMessage),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveAccessRequest' : IDL.Func([UserId, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([UserId], [], []),
    'createThread' : IDL.Func([IDL.Vec(UserId)], [ThreadId], []),
    'deleteMessage' : IDL.Func([ThreadId, MessageId], [], []),
    'deleteThread' : IDL.Func([ThreadId], [], []),
    'editMessage' : IDL.Func([ThreadId, MessageId, IDL.Text], [], []),
    'getAccessEntitlement' : IDL.Func(
        [UserId],
        [IDL.Opt(AccessEntitlement)],
        ['query'],
      ),
    'getAllAccessEntitlements' : IDL.Func(
        [],
        [IDL.Vec(AccessEntitlement)],
        ['query'],
      ),
    'getBlockedUsers' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUserAccessEntitlement' : IDL.Func(
        [],
        [IDL.Opt(AccessEntitlement)],
        ['query'],
      ),
    'getMessages' : IDL.Func([ThreadId], [IDL.Vec(ChatMessage)], ['query']),
    'getThread' : IDL.Func([ThreadId], [ChatThreadView], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserThreads' : IDL.Func([], [IDL.Vec(ThreadId)], ['query']),
    'grantAccess' : IDL.Func(
        [UserId, EntitlementType, EntitlementSource, IDL.Opt(IDL.Int)],
        [],
        [],
      ),
    'hasAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'hasBlocked' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([IDL.Opt(IDL.Text)], [UserProfile], []),
    'requestAccess' : IDL.Func([], [IDL.Bool], []),
    'revokeAccess' : IDL.Func([UserId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([ThreadId, IDL.Text], [MessageId], []),
    'switchToTemporaryAccess' : IDL.Func([UserId, IDL.Int], [], []),
    'unblockUser' : IDL.Func([UserId], [], []),
    'userExists' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };