/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ThreadId = bigint;
export type UserId = Principal;
export type MessageId = bigint;
export interface ChatMessage {
    id: MessageId;
    deleted: boolean;
    content: string;
    sender: UserId;
    timestamp: bigint;
}
export interface ChatThreadView {
    id: ThreadId;
    participants: Array<UserId>;
    messages: Array<ChatMessage>;
}
export interface AccessEntitlement {
    startTime: bigint;
    status: AccessRequestStatus;
    endTime?: bigint;
    source: EntitlementSource;
    user: UserId;
    entitlementType: EntitlementType;
    requestTimestamp: bigint;
}
export interface UserProfile {
    principal: UserId;
    displayName?: string;
}
export enum AccessRequestStatus {
    expired = "expired",
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum EntitlementSource {
    promotion = "promotion",
    adminGrant = "adminGrant",
    payment = "payment"
}
export enum EntitlementType {
    trial = "trial",
    permanent = "permanent",
    subscription = "subscription",
    sponsored = "sponsored"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveAccessRequest(user: UserId, approve: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(userToBlock: UserId): Promise<void>;
    createThread(participants: Array<UserId>): Promise<ThreadId>;
    deleteMessage(threadId: ThreadId, messageId: MessageId): Promise<void>;
    deleteThread(threadId: ThreadId): Promise<void>;
    editMessage(threadId: ThreadId, messageId: MessageId, newContent: string): Promise<void>;
    getAccessEntitlement(user: UserId): Promise<AccessEntitlement | null>;
    getAllAccessEntitlements(): Promise<Array<AccessEntitlement>>;
    getBlockedUsers(): Promise<Array<UserId>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentUserAccessEntitlement(): Promise<AccessEntitlement | null>;
    getMessages(threadId: ThreadId): Promise<Array<ChatMessage>>;
    getThread(threadId: ThreadId): Promise<ChatThreadView>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserThreads(): Promise<Array<ThreadId>>;
    grantAccess(user: UserId, entitlementType: EntitlementType, source: EntitlementSource, durationSeconds: bigint | null): Promise<void>;
    hasAccess(): Promise<boolean>;
    hasBlocked(other: UserId): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    registerUser(displayName: string | null): Promise<UserProfile>;
    requestAccess(): Promise<boolean>;
    revokeAccess(user: UserId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(threadId: ThreadId, content: string): Promise<MessageId>;
    switchToTemporaryAccess(user: UserId, duration: bigint): Promise<void>;
    unblockUser(userToUnblock: UserId): Promise<void>;
    userExists(): Promise<boolean>;
}
import type { AccessEntitlement as _AccessEntitlement, AccessRequestStatus as _AccessRequestStatus, EntitlementSource as _EntitlementSource, EntitlementType as _EntitlementType, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveAccessRequest(arg0: UserId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveAccessRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveAccessRequest(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async createThread(arg0: Array<UserId>): Promise<ThreadId> {
        if (this.processError) {
            try {
                const result = await this.actor.createThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createThread(arg0);
            return result;
        }
    }
    async deleteMessage(arg0: ThreadId, arg1: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0, arg1);
            return result;
        }
    }
    async deleteThread(arg0: ThreadId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteThread(arg0);
            return result;
        }
    }
    async editMessage(arg0: ThreadId, arg1: MessageId, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async getAccessEntitlement(arg0: UserId): Promise<AccessEntitlement | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessEntitlement(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessEntitlement(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAccessEntitlements(): Promise<Array<AccessEntitlement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAccessEntitlements();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAccessEntitlements();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlockedUsers(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentUserAccessEntitlement(): Promise<AccessEntitlement | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUserAccessEntitlement();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUserAccessEntitlement();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: ThreadId): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getThread(arg0: ThreadId): Promise<ChatThreadView> {
        if (this.processError) {
            try {
                const result = await this.actor.getThread(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThread(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserThreads(): Promise<Array<ThreadId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserThreads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserThreads();
            return result;
        }
    }
    async grantAccess(arg0: UserId, arg1: EntitlementType, arg2: EntitlementSource, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantAccess(arg0, to_candid_EntitlementType_n20(this._uploadFile, this._downloadFile, arg1), to_candid_EntitlementSource_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantAccess(arg0, to_candid_EntitlementType_n20(this._uploadFile, this._downloadFile, arg1), to_candid_EntitlementSource_n22(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async hasAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAccess();
            return result;
        }
    }
    async hasBlocked(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasBlocked(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasBlocked(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerUser(arg0: string | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_opt_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.requestAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestAccess();
            return result;
        }
    }
    async revokeAccess(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeAccess(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: ThreadId, arg1: string): Promise<MessageId> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async switchToTemporaryAccess(arg0: UserId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.switchToTemporaryAccess(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.switchToTemporaryAccess(arg0, arg1);
            return result;
        }
    }
    async unblockUser(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async userExists(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.userExists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.userExists();
            return result;
        }
    }
}
function from_candid_AccessEntitlement_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessEntitlement): AccessEntitlement {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_AccessRequestStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccessRequestStatus): AccessRequestStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_EntitlementSource_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntitlementSource): EntitlementSource {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_EntitlementType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EntitlementType): EntitlementType {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccessEntitlement]): AccessEntitlement | null {
    return value.length === 0 ? null : from_candid_AccessEntitlement_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    displayName: [] | [string];
}): {
    principal: UserId;
    displayName?: string;
} {
    return {
        principal: value.principal,
        displayName: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.displayName))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    status: _AccessRequestStatus;
    endTime: [] | [bigint];
    source: _EntitlementSource;
    user: _UserId;
    entitlementType: _EntitlementType;
    requestTimestamp: bigint;
}): {
    startTime: bigint;
    status: AccessRequestStatus;
    endTime?: bigint;
    source: EntitlementSource;
    user: UserId;
    entitlementType: EntitlementType;
    requestTimestamp: bigint;
} {
    return {
        startTime: value.startTime,
        status: from_candid_AccessRequestStatus_n6(_uploadFile, _downloadFile, value.status),
        endTime: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.endTime)),
        source: from_candid_EntitlementSource_n9(_uploadFile, _downloadFile, value.source),
        user: value.user,
        entitlementType: from_candid_EntitlementType_n11(_uploadFile, _downloadFile, value.entitlementType),
        requestTimestamp: value.requestTimestamp
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    promotion: null;
} | {
    adminGrant: null;
} | {
    payment: null;
}): EntitlementSource {
    return "promotion" in value ? EntitlementSource.promotion : "adminGrant" in value ? EntitlementSource.adminGrant : "payment" in value ? EntitlementSource.payment : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    permanent: null;
} | {
    subscription: null;
} | {
    sponsored: null;
}): EntitlementType {
    return "trial" in value ? EntitlementType.trial : "permanent" in value ? EntitlementType.permanent : "subscription" in value ? EntitlementType.subscription : "sponsored" in value ? EntitlementType.sponsored : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expired: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): AccessRequestStatus {
    return "expired" in value ? AccessRequestStatus.expired : "pending" in value ? AccessRequestStatus.pending : "approved" in value ? AccessRequestStatus.approved : "rejected" in value ? AccessRequestStatus.rejected : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AccessEntitlement>): Array<AccessEntitlement> {
    return value.map((x)=>from_candid_AccessEntitlement_n4(_uploadFile, _downloadFile, x));
}
function to_candid_EntitlementSource_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntitlementSource): _EntitlementSource {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_EntitlementType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntitlementType): _EntitlementType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: UserId;
    displayName?: string;
}): {
    principal: _UserId;
    displayName: [] | [string];
} {
    return {
        principal: value.principal,
        displayName: value.displayName ? candid_some(value.displayName) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntitlementType): {
    trial: null;
} | {
    permanent: null;
} | {
    subscription: null;
} | {
    sponsored: null;
} {
    return value == EntitlementType.trial ? {
        trial: null
    } : value == EntitlementType.permanent ? {
        permanent: null
    } : value == EntitlementType.subscription ? {
        subscription: null
    } : value == EntitlementType.sponsored ? {
        sponsored: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntitlementSource): {
    promotion: null;
} | {
    adminGrant: null;
} | {
    payment: null;
} {
    return value == EntitlementSource.promotion ? {
        promotion: null
    } : value == EntitlementSource.adminGrant ? {
        adminGrant: null
    } : value == EntitlementSource.payment ? {
        payment: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
